# Generated by Django 2.2.7 on 2019-12-03 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opc_ua', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=20)),
                ('bit', models.IntegerField()),
                ('text', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MessageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=20)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opc_ua.Server')),
            ],
        ),
        migrations.CreateModel(
            name='MessageEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_dt', models.DateTimeField()),
                ('ask_dt', models.DateTimeField(blank=True)),
                ('bit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opc_ua.MessageBit')),
            ],
        ),
        migrations.AddField(
            model_name='messagebit',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opc_ua.MessageTag'),
        ),
    ]
