# Generated by Django 2.2.7 on 2019-12-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opc_ua', '0002_auto_20191203_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagebit',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
