# Generated by Django 2.2.7 on 2019-12-03 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opc_ua', '0003_auto_20191203_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagebit',
            name='enable',
        ),
    ]
