# Generated by Django 2.2.7 on 2019-12-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opc_ua', '0004_remove_messagebit_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageevent',
            name='ask_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
