# Generated by Django 2.2.7 on 2019-12-04 13:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('opc_ua', '0005_auto_20191203_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageevent',
            name='event_dt',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 4, 13, 35, 9, 758200, tzinfo=utc)),
        ),
    ]
