# Generated by Django 2.2.7 on 2020-01-04 09:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('opc_ua', '0007_auto_20191219_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageevent',
            name='event_dt',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 4, 9, 8, 7, 32770, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='ResultOneMinute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(default=1)),
                ('lost_time', models.DateTimeField()),
                ('value', models.TextField(default='[]')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opc_ua.Tag')),
            ],
        ),
    ]
