# Generated by Django 2.2.7 on 2020-01-04 09:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('opc_ua', '0008_auto_20200104_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageevent',
            name='event_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
